---
- name: Create .ssh directory for root
  become: true
  file:
    path: /root/.ssh
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Delete git clone dir
  become: true
  shell: |
    rm -rf /home/isucon/isucon12-final /tmp/isucon-go-only

- name: Clone isucon12f from isucon-go-only (sparse)
  become: true
  shell: |
    git clone --depth=1 --filter=blob:none --sparse https://github.com/team-hacker-isucon/isucon-go-only.git /tmp/isucon-go-only
    git -C /tmp/isucon-go-only sparse-checkout set isucon12f
    mv /tmp/isucon-go-only/isucon12f /home/isucon/isucon12-final
    rm -rf /tmp/isucon-go-only

- name: Change owner of isucon12-final
  become: true
  file:
    path: /home/isucon/isucon12-final
    state: directory
    owner: isucon
    group: isucon
    recurse: true
